### ISSUE TITLE
Feedback for /docs/latest/python/python-appapi-devguide/

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.documentation#80]
1) In step 4, installing CPython: it should be noted that if compiling Python from source, the "--enable-shared" flag should be used when running './configure'. Otherwise, attempting to run an application will result in the following error: 

```
SEVERE: /usr/bin/ld: /usr/local/lib/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
Apr 29, 2016 9:09:17 AM com.ibm.streamsx.topology.internal.process.ProcessOutputToLogger run
SEVERE: /usr/local/lib/libpython3.5m.a: could not read symbols: Bad value
Apr 29, 2016 9:09:17 AM com.ibm.streamsx.topology.internal.process.ProcessOutputToLogger run
SEVERE: collect2: error: ld returned 1 exit status
Apr 29, 2016 9:09:17 AM com.ibm.streamsx.topology.internal.process.ProcessOutputToLogger run
SEVERE: make: *** [bin/temperature_sensor.temperature_sensor-a.dpe] Error 1
Apr 29, 2016 9:09:17 AM com.ibm.streamsx.topology.internal.process.ProcessOutputToLogger run
SEVERE: CDISP0141E ERROR: The compilation of the generated code failed.
Apr 29, 2016 9:09:17 AM com.ibm.streamsx.topology.internal.streams.InvokeSc invoke
INFO: SPL compiler complete: return code=1
Exception in thread "main" java.lang.Exception: SPL compilation failed!
    at com.ibm.streamsx.topology.internal.streams.InvokeSc.invoke(InvokeSc.java:119)
    at com.ibm.streamsx.topology.internal.context.BundleStreamsContext.doSPLCompile(BundleStreamsContext.java:102)
    at com.ibm.streamsx.topology.internal.context.BundleStreamsContext.submit(BundleStreamsContext.java:75)
    at com.ibm.streamsx.topology.internal.context.StandaloneStreamsContext.submit(StandaloneStreamsContext.java:52)
    at com.ibm.streamsx.topology.context.StreamsContextSubmit.main(StreamsContextSubmit.java:26)
```

2) The README.md file in the 'python' branch indicates that the LD_LIBRARY_PATH env var needs to be setup, but this doesn't appear in the dev guide. I recommend adding this as part of step 5, as this may be necessary (at least it was in my environment).

**Comment by chanskw** [comment]
@juliabamford Can you please take a look at this?

**Comment by ddebrunner** [comment]
See: https://github.com/IBMStreams/streamsx.topology/wiki/Installing-Python-and-com.ibm.streamsx.topology-Python-alpha

**Comment by markheger** [comment]
no longer valid
